# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  catppuccin = {
    pname = "catppuccin";
    version = "16408d203973da7e43fab87c6f9d3bf7fa98fa8b";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "nvim";
      rev = "16408d203973da7e43fab87c6f9d3bf7fa98fa8b";
      fetchSubmodules = false;
      sha256 = "sha256-C+bsDGpXwuie67yCFQjbqg6POC+y94eBIz9zxqo9jGM=";
    };
    date = "2026-04-02";
  };
  ddc-filter-converter_remove_overlap = {
    pname = "ddc-filter-converter_remove_overlap";
    version = "965503e08e33c505e54ee132fc4ae623bf78c88d";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddc-filter-converter_remove_overlap";
      rev = "965503e08e33c505e54ee132fc4ae623bf78c88d";
      fetchSubmodules = false;
      sha256 = "sha256-dSob16PMRWIn0Qy1C3DCJmR+im+aqBSCR5/P1ZrhODA=";
    };
    date = "2025-09-02";
  };
  ddc-filter-matcher_head = {
    pname = "ddc-filter-matcher_head";
    version = "7a955d2f6a44e39687459f8f3a22f4daa063a981";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddc-filter-matcher_head";
      rev = "7a955d2f6a44e39687459f8f3a22f4daa063a981";
      fetchSubmodules = false;
      sha256 = "sha256-VYNjVH1OtmSyvBoFxF5WBf150GwoIpjTe0Y0oK8Hp8A=";
    };
    date = "2025-09-02";
  };
  ddc-filter-matcher_length = {
    pname = "ddc-filter-matcher_length";
    version = "0d4f4a6dd657c3394e522910a7bdc2f15f587b52";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddc-filter-matcher_length";
      rev = "0d4f4a6dd657c3394e522910a7bdc2f15f587b52";
      fetchSubmodules = false;
      sha256 = "sha256-rihHC4tqHGId6F9/0vfqSSOHkPAxHT8M7xSHTeFqffM=";
    };
    date = "2025-09-02";
  };
  ddc-filter-matcher_prefix = {
    pname = "ddc-filter-matcher_prefix";
    version = "76c5b1f0eec7263ad56bc40e4811a88faf1a3874";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddc-filter-matcher_prefix";
      rev = "76c5b1f0eec7263ad56bc40e4811a88faf1a3874";
      fetchSubmodules = false;
      sha256 = "sha256-l2lHrFI1A5P4p+xno3dgme9kF7KeDU1kdBlrNOakraU=";
    };
    date = "2025-09-02";
  };
  ddc-filter-sorter_head = {
    pname = "ddc-filter-sorter_head";
    version = "6e78a3db9fa3334149b9ff62aebdb37de3048865";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddc-filter-sorter_head";
      rev = "6e78a3db9fa3334149b9ff62aebdb37de3048865";
      fetchSubmodules = false;
      sha256 = "sha256-8obtf/tJhL1LUYmlQwfosHHWUGLVkKlvZLbju/RvtoU=";
    };
    date = "2025-09-02";
  };
  ddc-filter-sorter_lsp_kind = {
    pname = "ddc-filter-sorter_lsp_kind";
    version = "2d082e521f6e0f8d452ad737145315606eaec532";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddc-filter-sorter_lsp_kind";
      rev = "2d082e521f6e0f8d452ad737145315606eaec532";
      fetchSubmodules = false;
      sha256 = "sha256-ejTiozAzDdDi68KujdiUgaTZtuHnseqd+IhTzchK5Mw=";
    };
    date = "2025-09-08";
  };
  ddc-filter-sorter_rank = {
    pname = "ddc-filter-sorter_rank";
    version = "eed3cb33b3ae3f9128257fcfb95e0511d1b13891";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddc-filter-sorter_rank";
      rev = "eed3cb33b3ae3f9128257fcfb95e0511d1b13891";
      fetchSubmodules = false;
      sha256 = "sha256-8zoRsX7ZNCNkokku0TW0LNkjXmBL8UCu8h3EAe4KQ+g=";
    };
    date = "2025-09-02";
  };
  ddc-source-around = {
    pname = "ddc-source-around";
    version = "68e679ca0b989cfe3300acac9099b893d0675063";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddc-source-around";
      rev = "68e679ca0b989cfe3300acac9099b893d0675063";
      fetchSubmodules = false;
      sha256 = "sha256-wLQ9vpKgl4fyjLEWo1XIElw8CbFjpBkvYMFoMPrQTxM=";
    };
    date = "2025-09-03";
  };
  ddc-source-buffer = {
    pname = "ddc-source-buffer";
    version = "bc2416de3629693f88e66870ca11090571f265ec";
    src = fetchFromGitHub {
      owner = "matsui54";
      repo = "ddc-source-buffer";
      rev = "bc2416de3629693f88e66870ca11090571f265ec";
      fetchSubmodules = false;
      sha256 = "sha256-snNlvHeIGsi7Iz36AWItf7IsVHopvrsEmDTf0MR8mUw=";
    };
    date = "2025-09-15";
  };
  ddc-source-file = {
    pname = "ddc-source-file";
    version = "e2386ed1e6739f48d4f3cfea9cc961fb5785480a";
    src = fetchFromGitHub {
      owner = "LumaKernel";
      repo = "ddc-source-file";
      rev = "e2386ed1e6739f48d4f3cfea9cc961fb5785480a";
      fetchSubmodules = false;
      sha256 = "sha256-UndfTc+awrlzJUziPEv5FFwwDjQTSqOVZXheQ/CERpg=";
    };
    date = "2025-09-03";
  };
  ddc-source-lsp = {
    pname = "ddc-source-lsp";
    version = "352f804c08dbc6ce516234bb97309a5b78a1863f";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddc-source-lsp";
      rev = "352f804c08dbc6ce516234bb97309a5b78a1863f";
      fetchSubmodules = false;
      sha256 = "sha256-oj+L2dy6FpOYv/j0E/tsSD0BfP9qTtWCKwrLZSsCUsc=";
    };
    date = "2026-03-22";
  };
  ddc-ui-pum = {
    pname = "ddc-ui-pum";
    version = "f7f334380e18af42297468b3cf696794bbfa2652";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddc-ui-pum";
      rev = "f7f334380e18af42297468b3cf696794bbfa2652";
      fetchSubmodules = false;
      sha256 = "sha256-kQ1fK65V0NtObqBy/FhcfACUGeI5Pk4t3Kw0BPpxChw=";
    };
    date = "2025-08-26";
  };
  ddc-vim = {
    pname = "ddc-vim";
    version = "033f556bedd32e2284dfa477562624f6d2f9166e";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddc.vim";
      rev = "033f556bedd32e2284dfa477562624f6d2f9166e";
      fetchSubmodules = false;
      sha256 = "sha256-lQCoMfaGkIOaJWO0fo266MAN9vupyNbMlWYACzWeZiA=";
    };
    date = "2026-03-25";
  };
  denops-popup-preview-vim = {
    pname = "denops-popup-preview-vim";
    version = "6ba396dfb6321b2d5a0f6782823d6e588089e596";
    src = fetchFromGitHub {
      owner = "matsui54";
      repo = "denops-popup-preview.vim";
      rev = "6ba396dfb6321b2d5a0f6782823d6e588089e596";
      fetchSubmodules = false;
      sha256 = "sha256-L3Gr+BfszlFHvmxA8M8+jJ73akQzetkX/RoLVsEB4hE=";
    };
    date = "2025-08-11";
  };
  denops-signature_help = {
    pname = "denops-signature_help";
    version = "f56884f3eed5af6c13cc414a092ce05ca9ad2612";
    src = fetchFromGitHub {
      owner = "matsui54";
      repo = "denops-signature_help";
      rev = "f56884f3eed5af6c13cc414a092ce05ca9ad2612";
      fetchSubmodules = false;
      sha256 = "sha256-5V4Joj0mTUEFVz/c2y9cMHA7DKJEZuL1OeGlyf04xhI=";
    };
    date = "2026-02-01";
  };
  denops-vim = {
    pname = "denops-vim";
    version = "1df7a022d6e9cb3f6a3db43235e0f174ccd79e03";
    src = fetchFromGitHub {
      owner = "vim-denops";
      repo = "denops.vim";
      rev = "1df7a022d6e9cb3f6a3db43235e0f174ccd79e03";
      fetchSubmodules = false;
      sha256 = "sha256-lj8yjZrwE9GfNPDIpH4tCI4TTJHkYRlFFCTdqMqWtZg=";
    };
    date = "2026-03-22";
  };
  nvim-aibo = {
    pname = "nvim-aibo";
    version = "bcbeab88c27cf831a08661eace7a928b2bba5694";
    src = fetchFromGitHub {
      owner = "lambdalisue";
      repo = "nvim-aibo";
      rev = "bcbeab88c27cf831a08661eace7a928b2bba5694";
      fetchSubmodules = false;
      sha256 = "sha256-H/bhobPLhIpNI5Zk4sWdiisgULQTXGtsUzDO0CUPTdw=";
    };
    date = "2026-02-25";
  };
  nvim-lspconfig = {
    pname = "nvim-lspconfig";
    version = "9ccd58a7949091c0cc2777d4e92a45a209c808c1";
    src = fetchFromGitHub {
      owner = "neovim";
      repo = "nvim-lspconfig";
      rev = "9ccd58a7949091c0cc2777d4e92a45a209c808c1";
      fetchSubmodules = false;
      sha256 = "sha256-t8iFoSJGODxHhxZbg2kUapNKUHK08IjCfeafGEDO28g=";
    };
    date = "2026-04-03";
  };
  pum-vim = {
    pname = "pum-vim";
    version = "69aafe85ccbe001da3c709875e2af8051f8f421f";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "pum.vim";
      rev = "69aafe85ccbe001da3c709875e2af8051f8f421f";
      fetchSubmodules = false;
      sha256 = "sha256-wa1i0gqOUK3SAT5NVZypDSGAHX3kvybntX9C5I2zRm8=";
    };
    date = "2026-03-30";
  };
  skk-dict = {
    pname = "skk-dict";
    version = "4eb91a3bbfef70bde940668ec60f3beae291e971";
    src = fetchFromGitHub {
      owner = "skk-dev";
      repo = "dict";
      rev = "4eb91a3bbfef70bde940668ec60f3beae291e971";
      fetchSubmodules = false;
      sha256 = "sha256-sWz85Q6Bu2WoKsckSp5SlcuPUQN2mcq+BHMqNXQ/aho=";
    };
    date = "2024-08-29";
  };
  skkeleton = {
    pname = "skkeleton";
    version = "b530eac5a859ce2f8fa4d99fa5cd83b9d3199086";
    src = fetchFromGitHub {
      owner = "vim-skk";
      repo = "skkeleton";
      rev = "b530eac5a859ce2f8fa4d99fa5cd83b9d3199086";
      fetchSubmodules = false;
      sha256 = "sha256-OhHlG3ngNbvUSNqS/MFJpYI/cfbkxSxTPo8EiSwW/MU=";
    };
    date = "2026-04-02";
  };
  skkeleton-henkan-highlight = {
    pname = "skkeleton-henkan-highlight";
    version = "361ca90537e9cf7cd404899a4ed0bbef03124fd8";
    src = fetchFromGitHub {
      owner = "NI57721";
      repo = "skkeleton-henkan-highlight";
      rev = "361ca90537e9cf7cd404899a4ed0bbef03124fd8";
      fetchSubmodules = false;
      sha256 = "sha256-haDXPCyOkK4F0LMNR8yU+nL87hijwON1QpjmsJtv7gE=";
    };
    date = "2025-12-11";
  };
  skkeleton-state-popup = {
    pname = "skkeleton-state-popup";
    version = "e09dcbf85073df53c9c8d960f6160818572c1397";
    src = fetchFromGitHub {
      owner = "NI57721";
      repo = "skkeleton-state-popup";
      rev = "e09dcbf85073df53c9c8d960f6160818572c1397";
      fetchSubmodules = false;
      sha256 = "sha256-rUQ93m1jdopyFXH9KVmoTnNci8WsVz5472v+z115QoE=";
    };
    date = "2026-01-17";
  };
  vim-gin = {
    pname = "vim-gin";
    version = "726a2eede0f03e97507ec99ea20cba83f8eb086e";
    src = fetchFromGitHub {
      owner = "lambdalisue";
      repo = "vim-gin";
      rev = "726a2eede0f03e97507ec99ea20cba83f8eb086e";
      fetchSubmodules = false;
      sha256 = "sha256-8Dhpup9MUKCcsi6im+sOxv9lUHvlLgpd9YISmkjjIHs=";
    };
    date = "2026-02-07";
  };
  vim-guise = {
    pname = "vim-guise";
    version = "eae13cebec562dda4378765da3b9044bde81d07a";
    src = fetchFromGitHub {
      owner = "lambdalisue";
      repo = "vim-guise";
      rev = "eae13cebec562dda4378765da3b9044bde81d07a";
      fetchSubmodules = false;
      sha256 = "sha256-WgmjJa/pzLSZNy9d/TiwGS2q+GQrFj1ZHfodc3RzPu0=";
    };
    date = "2025-12-18";
  };
}
