# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  ddc-filter-converter_remove_overlap = {
    pname = "ddc-filter-converter_remove_overlap";
    version = "965503e08e33c505e54ee132fc4ae623bf78c88d";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddc-filter-converter_remove_overlap";
      rev = "965503e08e33c505e54ee132fc4ae623bf78c88d";
      fetchSubmodules = false;
      sha256 = "sha256-dSob16PMRWIn0Qy1C3DCJmR+im+aqBSCR5/P1ZrhODA=";
    };
    date = "2025-09-02";
  };
  ddc-filter-matcher_head = {
    pname = "ddc-filter-matcher_head";
    version = "7a955d2f6a44e39687459f8f3a22f4daa063a981";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddc-filter-matcher_head";
      rev = "7a955d2f6a44e39687459f8f3a22f4daa063a981";
      fetchSubmodules = false;
      sha256 = "sha256-VYNjVH1OtmSyvBoFxF5WBf150GwoIpjTe0Y0oK8Hp8A=";
    };
    date = "2025-09-02";
  };
  ddc-filter-matcher_length = {
    pname = "ddc-filter-matcher_length";
    version = "0d4f4a6dd657c3394e522910a7bdc2f15f587b52";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddc-filter-matcher_length";
      rev = "0d4f4a6dd657c3394e522910a7bdc2f15f587b52";
      fetchSubmodules = false;
      sha256 = "sha256-rihHC4tqHGId6F9/0vfqSSOHkPAxHT8M7xSHTeFqffM=";
    };
    date = "2025-09-02";
  };
  ddc-filter-matcher_prefix = {
    pname = "ddc-filter-matcher_prefix";
    version = "76c5b1f0eec7263ad56bc40e4811a88faf1a3874";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddc-filter-matcher_prefix";
      rev = "76c5b1f0eec7263ad56bc40e4811a88faf1a3874";
      fetchSubmodules = false;
      sha256 = "sha256-l2lHrFI1A5P4p+xno3dgme9kF7KeDU1kdBlrNOakraU=";
    };
    date = "2025-09-02";
  };
  ddc-filter-sorter_head = {
    pname = "ddc-filter-sorter_head";
    version = "6e78a3db9fa3334149b9ff62aebdb37de3048865";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddc-filter-sorter_head";
      rev = "6e78a3db9fa3334149b9ff62aebdb37de3048865";
      fetchSubmodules = false;
      sha256 = "sha256-8obtf/tJhL1LUYmlQwfosHHWUGLVkKlvZLbju/RvtoU=";
    };
    date = "2025-09-02";
  };
  ddc-filter-sorter_lsp_kind = {
    pname = "ddc-filter-sorter_lsp_kind";
    version = "2d082e521f6e0f8d452ad737145315606eaec532";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddc-filter-sorter_lsp_kind";
      rev = "2d082e521f6e0f8d452ad737145315606eaec532";
      fetchSubmodules = false;
      sha256 = "sha256-ejTiozAzDdDi68KujdiUgaTZtuHnseqd+IhTzchK5Mw=";
    };
    date = "2025-09-08";
  };
  ddc-filter-sorter_rank = {
    pname = "ddc-filter-sorter_rank";
    version = "eed3cb33b3ae3f9128257fcfb95e0511d1b13891";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddc-filter-sorter_rank";
      rev = "eed3cb33b3ae3f9128257fcfb95e0511d1b13891";
      fetchSubmodules = false;
      sha256 = "sha256-8zoRsX7ZNCNkokku0TW0LNkjXmBL8UCu8h3EAe4KQ+g=";
    };
    date = "2025-09-02";
  };
  ddc-source-around = {
    pname = "ddc-source-around";
    version = "68e679ca0b989cfe3300acac9099b893d0675063";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddc-source-around";
      rev = "68e679ca0b989cfe3300acac9099b893d0675063";
      fetchSubmodules = false;
      sha256 = "sha256-wLQ9vpKgl4fyjLEWo1XIElw8CbFjpBkvYMFoMPrQTxM=";
    };
    date = "2025-09-03";
  };
  ddc-source-buffer = {
    pname = "ddc-source-buffer";
    version = "bc2416de3629693f88e66870ca11090571f265ec";
    src = fetchFromGitHub {
      owner = "matsui54";
      repo = "ddc-source-buffer";
      rev = "bc2416de3629693f88e66870ca11090571f265ec";
      fetchSubmodules = false;
      sha256 = "sha256-snNlvHeIGsi7Iz36AWItf7IsVHopvrsEmDTf0MR8mUw=";
    };
    date = "2025-09-15";
  };
  ddc-source-file = {
    pname = "ddc-source-file";
    version = "e2386ed1e6739f48d4f3cfea9cc961fb5785480a";
    src = fetchFromGitHub {
      owner = "LumaKernel";
      repo = "ddc-source-file";
      rev = "e2386ed1e6739f48d4f3cfea9cc961fb5785480a";
      fetchSubmodules = false;
      sha256 = "sha256-UndfTc+awrlzJUziPEv5FFwwDjQTSqOVZXheQ/CERpg=";
    };
    date = "2025-09-03";
  };
  ddc-source-lsp = {
    pname = "ddc-source-lsp";
    version = "012b42673faaf65c55327d4bd6e38378fcf29030";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddc-source-lsp";
      rev = "012b42673faaf65c55327d4bd6e38378fcf29030";
      fetchSubmodules = false;
      sha256 = "sha256-L81ttrA1tXB2RPwVyfjtphnJAIYZAC3eHc7PKfAkFQY=";
    };
    date = "2025-09-13";
  };
  ddc-ui-pum = {
    pname = "ddc-ui-pum";
    version = "f7f334380e18af42297468b3cf696794bbfa2652";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddc-ui-pum";
      rev = "f7f334380e18af42297468b3cf696794bbfa2652";
      fetchSubmodules = false;
      sha256 = "sha256-kQ1fK65V0NtObqBy/FhcfACUGeI5Pk4t3Kw0BPpxChw=";
    };
    date = "2025-08-26";
  };
  ddc-vim = {
    pname = "ddc-vim";
    version = "ef527ad60b199b11d022a648a24ab6d424227943";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddc.vim";
      rev = "ef527ad60b199b11d022a648a24ab6d424227943";
      fetchSubmodules = false;
      sha256 = "sha256-Gp6xenZrXPl2UZ1W5yFvolWUW/rWzxGyVDY8lVcA0WA=";
    };
    date = "2025-11-16";
  };
  denops-popup-preview-vim = {
    pname = "denops-popup-preview-vim";
    version = "6ba396dfb6321b2d5a0f6782823d6e588089e596";
    src = fetchFromGitHub {
      owner = "matsui54";
      repo = "denops-popup-preview.vim";
      rev = "6ba396dfb6321b2d5a0f6782823d6e588089e596";
      fetchSubmodules = false;
      sha256 = "sha256-L3Gr+BfszlFHvmxA8M8+jJ73akQzetkX/RoLVsEB4hE=";
    };
    date = "2025-08-11";
  };
  denops-signature_help = {
    pname = "denops-signature_help";
    version = "53cdd50c4f3d2bb45d66af3402f008cbeaa1cfe3";
    src = fetchFromGitHub {
      owner = "matsui54";
      repo = "denops-signature_help";
      rev = "53cdd50c4f3d2bb45d66af3402f008cbeaa1cfe3";
      fetchSubmodules = false;
      sha256 = "sha256-WFk96DOXdkcgIzehMrIyIZBcE0sPGTbBHzazmN3SZQ0=";
    };
    date = "2025-08-15";
  };
  denops-vim = {
    pname = "denops-vim";
    version = "5cfca39988a36e42d81b925264fc846077a727e3";
    src = fetchFromGitHub {
      owner = "vim-denops";
      repo = "denops.vim";
      rev = "5cfca39988a36e42d81b925264fc846077a727e3";
      fetchSubmodules = false;
      sha256 = "sha256-4AACZ3h6uAqiXW24gUF1+uq7dnWA0w/PcxAeO4yxitc=";
    };
    date = "2025-10-26";
  };
  moonbit = {
    pname = "moonbit";
    version = "f49215a47f8c9928894358b204e4813e127ba08e";
    src = fetchFromGitHub {
      owner = "moonbit-community";
      repo = "moonbit.nvim";
      rev = "f49215a47f8c9928894358b204e4813e127ba08e";
      fetchSubmodules = false;
      sha256 = "sha256-ZhM0vnNzn8JP5KUblBCC9hQBC9bmGfDGEEKfPkFMBzQ=";
    };
    date = "2025-07-09";
  };
  nvim-aibo = {
    pname = "nvim-aibo";
    version = "ede45dca805afab44941046088dacc031086d6b2";
    src = fetchFromGitHub {
      owner = "lambdalisue";
      repo = "nvim-aibo";
      rev = "ede45dca805afab44941046088dacc031086d6b2";
      fetchSubmodules = false;
      sha256 = "sha256-1ZWuRBF6Qn6+HJHHdDZjUwbbt2+Nj6IN9BkHjkrfZks=";
    };
    date = "2025-12-18";
  };
  nvim-lspconfig = {
    pname = "nvim-lspconfig";
    version = "41ceb6bba3a40128b7841f5b7f5a9dae7201e823";
    src = fetchFromGitHub {
      owner = "neovim";
      repo = "nvim-lspconfig";
      rev = "41ceb6bba3a40128b7841f5b7f5a9dae7201e823";
      fetchSubmodules = false;
      sha256 = "sha256-qD7cSyGmAJO13nxEZYEr2FMsccJ/21LAw8L93BBTwk0=";
    };
    date = "2025-12-30";
  };
  pum-vim = {
    pname = "pum-vim";
    version = "fed31b9f117e4c10332c30108152a935496bc3b5";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "pum.vim";
      rev = "fed31b9f117e4c10332c30108152a935496bc3b5";
      fetchSubmodules = false;
      sha256 = "sha256-hOUvq4hXlj7fxaJ/8ng3vEH2t0NrnWKuCqr7TwfD28c=";
    };
    date = "2025-11-10";
  };
  skk-dict = {
    pname = "skk-dict";
    version = "4eb91a3bbfef70bde940668ec60f3beae291e971";
    src = fetchFromGitHub {
      owner = "skk-dev";
      repo = "dict";
      rev = "4eb91a3bbfef70bde940668ec60f3beae291e971";
      fetchSubmodules = false;
      sha256 = "sha256-sWz85Q6Bu2WoKsckSp5SlcuPUQN2mcq+BHMqNXQ/aho=";
    };
    date = "2024-08-29";
  };
  skkeleton = {
    pname = "skkeleton";
    version = "d2214e6d40fe4613f8e962e9086a4ae01fe8d088";
    src = fetchFromGitHub {
      owner = "vim-skk";
      repo = "skkeleton";
      rev = "d2214e6d40fe4613f8e962e9086a4ae01fe8d088";
      fetchSubmodules = false;
      sha256 = "sha256-Q632wC8tuG0OO0zkpy3J4kpA1zEhO8eN+KIj1clVrvA=";
    };
    date = "2025-12-15";
  };
  skkeleton-henkan-highlight = {
    pname = "skkeleton-henkan-highlight";
    version = "361ca90537e9cf7cd404899a4ed0bbef03124fd8";
    src = fetchFromGitHub {
      owner = "NI57721";
      repo = "skkeleton-henkan-highlight";
      rev = "361ca90537e9cf7cd404899a4ed0bbef03124fd8";
      fetchSubmodules = false;
      sha256 = "sha256-haDXPCyOkK4F0LMNR8yU+nL87hijwON1QpjmsJtv7gE=";
    };
    date = "2025-12-11";
  };
  skkeleton-state-popup = {
    pname = "skkeleton-state-popup";
    version = "2a72e33c47cc8762517d479c28f0deedde8b6794";
    src = fetchFromGitHub {
      owner = "NI57721";
      repo = "skkeleton-state-popup";
      rev = "2a72e33c47cc8762517d479c28f0deedde8b6794";
      fetchSubmodules = false;
      sha256 = "sha256-Zamd5GlFHpPrSiWVx3xK5EeUU8ZoEQf82yoBjQ7ypaM=";
    };
    date = "2025-11-05";
  };
  vim-gin = {
    pname = "vim-gin";
    version = "18478a2dee183c7e84543183844d2b3dd0440553";
    src = fetchFromGitHub {
      owner = "lambdalisue";
      repo = "vim-gin";
      rev = "18478a2dee183c7e84543183844d2b3dd0440553";
      fetchSubmodules = false;
      sha256 = "sha256-ylifuKrEPpH0NxfyMUj1Seg2OXutvrQW9Y9y2TGlw70=";
    };
    date = "2025-12-17";
  };
  vim-guise = {
    pname = "vim-guise";
    version = "eae13cebec562dda4378765da3b9044bde81d07a";
    src = fetchFromGitHub {
      owner = "lambdalisue";
      repo = "vim-guise";
      rev = "eae13cebec562dda4378765da3b9044bde81d07a";
      fetchSubmodules = false;
      sha256 = "sha256-WgmjJa/pzLSZNy9d/TiwGS2q+GQrFj1ZHfodc3RzPu0=";
    };
    date = "2025-12-18";
  };
}
