keys:
  - &admin "age170d6z6qazdvz3jtj90p8wrgw8j2vjqqa55jq8mkegkzrf4ch343qhjdfwg"
  - &warashi "age1fuedjsnapm4peln3ke9aq8rr3nvacke65gfhzqd8cg72qd7ntskq25yn2e"
  - &athena "age1w7xxgnxeuj37mdpq27wqhpf3td3rwnjtlcxgauvdyget8yfuuf3sax65tw"
  - &duna "age1l5uf3k2x5z0eprxhy5x7pvjt4pvtph6j4jct9sr6z07mupus3v3qjyu72w"
  - &workbench "age1zmyz7jedkp8kvkct2tgxg38t0cugn0crms6wjkv46xwnr8ycca4qn9vupe"
  - &work "age163zae0wt5vvvuuxdlxvt68zezyufu6dwz6ax5z7lk26kemypv9ws0pvldy"
  - &pi "age1axm5yfnhst7wxh7cgcm43wfdq4t80jaekgrfqqmprmzglqhrhdasjtmc97"
creation_rules:
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
      - age:
          - *admin
          - *warashi
          - *athena
          - *duna
          - *workbench
          - *work
          - *pi
