# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  Warashi-denovo-abbrev = {
    pname = "Warashi-denovo-abbrev";
    version = "20cff921d2fa9690ee7c83883529cd1928ac1850";
    src = fetchFromGitHub {
      owner = "Warashi";
      repo = "denovo-abbrev";
      rev = "20cff921d2fa9690ee7c83883529cd1928ac1850";
      fetchSubmodules = false;
      sha256 = "sha256-W3wlEmN5uVGizbF5sAueuFR0CQz5NVGqpyJJtAOOXIo=";
    };
    date = "2023-09-19";
  };
  Warashi-denovo-complete = {
    pname = "Warashi-denovo-complete";
    version = "b822fd0ae0ddd7e787de74f8f1630733730e3ea3";
    src = fetchFromGitHub {
      owner = "Warashi";
      repo = "denovo-complete";
      rev = "b822fd0ae0ddd7e787de74f8f1630733730e3ea3";
      fetchSubmodules = false;
      sha256 = "sha256-Jw/HTlLx1pGbbatcvvdxbMj9qzVr03KAh2Ga4R9zeT4=";
    };
    date = "2024-02-23";
  };
  Warashi-denovo-fzf = {
    pname = "Warashi-denovo-fzf";
    version = "5d9d2d681cd30bb233373a3969f790e34fe94db7";
    src = fetchFromGitHub {
      owner = "Warashi";
      repo = "denovo-fzf";
      rev = "5d9d2d681cd30bb233373a3969f790e34fe94db7";
      fetchSubmodules = false;
      sha256 = "sha256-YcCK2H+FoYXRWrVFehOOxe4FokJqMZ3DWU2tcajszHg=";
    };
    date = "2023-07-02";
  };
  Warashi-denovo-rootmake = {
    pname = "Warashi-denovo-rootmake";
    version = "9e4bf7c051cc99e4ada185959966f12bcdf47db3";
    src = fetchFromGitHub {
      owner = "Warashi";
      repo = "denovo-rootmake";
      rev = "9e4bf7c051cc99e4ada185959966f12bcdf47db3";
      fetchSubmodules = false;
      sha256 = "sha256-izHR+B1BzHPA3Ky5QfQThSjtSG3x3a9V308IzLsgaLo=";
    };
    date = "2025-05-31";
  };
  Warashi-denovo-zsh = {
    pname = "Warashi-denovo-zsh";
    version = "bd71f344ab5450a9b33b7ddb65dc4b8bda2310b5";
    src = fetchFromGitHub {
      owner = "Warashi";
      repo = "denovo.zsh";
      rev = "bd71f344ab5450a9b33b7ddb65dc4b8bda2310b5";
      fetchSubmodules = false;
      sha256 = "sha256-F3c+7OQDLbr56FX5GC+b6oVLpp8R7xHoh0MQkxf25xw=";
    };
    date = "2025-01-26";
  };
  trystan2k-zsh-tab-title = {
    pname = "trystan2k-zsh-tab-title";
    version = "9c36ac968fe675edcc181a41b0b8959024a8b6c1";
    src = fetchFromGitHub {
      owner = "trystan2k";
      repo = "zsh-tab-title";
      rev = "9c36ac968fe675edcc181a41b0b8959024a8b6c1";
      fetchSubmodules = false;
      sha256 = "sha256-ZEhbQ+yIfCz+vmua7XYBQ4kSVgwoNR8Y4zJyKNypsz0=";
    };
    date = "2024-05-29";
  };
}
