# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  Warashi-denovo-abbrev = {
    pname = "Warashi-denovo-abbrev";
    version = "44825bc4378c9021b9cfc1af8ebc929020c849f0";
    src = fetchFromGitHub {
      owner = "Warashi";
      repo = "denovo-abbrev";
      rev = "44825bc4378c9021b9cfc1af8ebc929020c849f0";
      fetchSubmodules = false;
      sha256 = "sha256-SGWFasNZEEMif4/3Sao5hyUrbGy/XTwTudi291bZJ6I=";
    };
    date = "2026-01-21";
  };
  Warashi-denovo-complete = {
    pname = "Warashi-denovo-complete";
    version = "b822fd0ae0ddd7e787de74f8f1630733730e3ea3";
    src = fetchFromGitHub {
      owner = "Warashi";
      repo = "denovo-complete";
      rev = "b822fd0ae0ddd7e787de74f8f1630733730e3ea3";
      fetchSubmodules = false;
      sha256 = "sha256-Jw/HTlLx1pGbbatcvvdxbMj9qzVr03KAh2Ga4R9zeT4=";
    };
    date = "2024-02-23";
  };
  Warashi-denovo-fzf = {
    pname = "Warashi-denovo-fzf";
    version = "5d9d2d681cd30bb233373a3969f790e34fe94db7";
    src = fetchFromGitHub {
      owner = "Warashi";
      repo = "denovo-fzf";
      rev = "5d9d2d681cd30bb233373a3969f790e34fe94db7";
      fetchSubmodules = false;
      sha256 = "sha256-YcCK2H+FoYXRWrVFehOOxe4FokJqMZ3DWU2tcajszHg=";
    };
    date = "2023-07-02";
  };
  Warashi-denovo-rootmake = {
    pname = "Warashi-denovo-rootmake";
    version = "9e4bf7c051cc99e4ada185959966f12bcdf47db3";
    src = fetchFromGitHub {
      owner = "Warashi";
      repo = "denovo-rootmake";
      rev = "9e4bf7c051cc99e4ada185959966f12bcdf47db3";
      fetchSubmodules = false;
      sha256 = "sha256-izHR+B1BzHPA3Ky5QfQThSjtSG3x3a9V308IzLsgaLo=";
    };
    date = "2025-05-31";
  };
  Warashi-denovo-zsh = {
    pname = "Warashi-denovo-zsh";
    version = "ae2b578143ed722331671150a2b035fa61ce1aec";
    src = fetchFromGitHub {
      owner = "Warashi";
      repo = "denovo.zsh";
      rev = "ae2b578143ed722331671150a2b035fa61ce1aec";
      fetchSubmodules = false;
      sha256 = "sha256-KMmojp5sMAxfvIdsOP7RGJ9t1rKtP9EsvKUqR+F6EeQ=";
    };
    date = "2026-01-22";
  };
  trystan2k-zsh-tab-title = {
    pname = "trystan2k-zsh-tab-title";
    version = "dfd469b704638dd596aba5695f1723a7c233fe4b";
    src = fetchFromGitHub {
      owner = "trystan2k";
      repo = "zsh-tab-title";
      rev = "dfd469b704638dd596aba5695f1723a7c233fe4b";
      fetchSubmodules = false;
      sha256 = "sha256-2mgK9fXRyiWWjy6TewqUmAZHaef+NEkCE4D0acNJ1jo=";
    };
    date = "2026-03-29";
  };
}
