# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  anthropics-skills = {
    pname = "anthropics-skills";
    version = "7029232b9212482c0476da354b83364bd28fab2f";
    src = fetchFromGitHub {
      owner = "anthropics";
      repo = "skills";
      rev = "7029232b9212482c0476da354b83364bd28fab2f";
      fetchSubmodules = false;
      sha256 = "sha256-rQXOcZk0nF9ZqYK0CUelGoY4oj/gYZgcdh1qUdwvx2k=";
    };
    date = "2026-03-04";
  };
  leanprover-skills = {
    pname = "leanprover-skills";
    version = "7d3da0282e7b724b07620e45cf212f2e05e19334";
    src = fetchFromGitHub {
      owner = "leanprover";
      repo = "skills";
      rev = "7d3da0282e7b724b07620e45cf212f2e05e19334";
      fetchSubmodules = false;
      sha256 = "sha256-wMGIyEwwM+R5B6pGtP/jsaA8KN2CDCE2SbNZ4b+REgk=";
    };
    date = "2026-02-21";
  };
}
