# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  anthropics-skills = {
    pname = "anthropics-skills";
    version = "98669c11ca63e9c81c11501e1437e5c47b556621";
    src = fetchFromGitHub {
      owner = "anthropics";
      repo = "skills";
      rev = "98669c11ca63e9c81c11501e1437e5c47b556621";
      fetchSubmodules = false;
      sha256 = "sha256-w//9LB1OVG9jlllY+VDse7Js0dn5x6Ys2vPuQACKsTM=";
    };
    date = "2026-03-25";
  };
  leanprover-skills = {
    pname = "leanprover-skills";
    version = "7d3da0282e7b724b07620e45cf212f2e05e19334";
    src = fetchFromGitHub {
      owner = "leanprover";
      repo = "skills";
      rev = "7d3da0282e7b724b07620e45cf212f2e05e19334";
      fetchSubmodules = false;
      sha256 = "sha256-wMGIyEwwM+R5B6pGtP/jsaA8KN2CDCE2SbNZ4b+REgk=";
    };
    date = "2026-02-21";
  };
}
