login-password: ENC[AES256_GCM,data:4/zjSvn0JBFrxjLcbMQHdZnqC2SfQIGDjOf8hScX8W1Yc2E9KGqTUqagLyDKUJWSgfG9z3xFlvi8hltOzA2CGkaA9k5s529R6A==,iv:/9uLUaN2rBcfWJoBlBvoLeLu7DUEDgAh7fOqJBD8KFw=,tag:br909IOYkQdyPdjEdEDSxg==,type:str]
tailscale-authkey: ENC[AES256_GCM,data:T/GtWgtaoe7F4oNYh9252kUYVHuaRCtTbPnVOwHmo1feBCe+5RXz6uF/Z/+z7XZZsCbJZM2YdUGeGySUCNg=,iv:nqUgadNEJlTXRxDXSezI5lLn+61nR7ArD7/Ip2IsdIE=,tag:09XhfRFfqFUL3S4UwkZGsA==,type:str]
age-public-key: ENC[AES256_GCM,data:eHfTFfnki8RQL+RTGLbjQmsMaqeUNpiJY8nnhPZYczGx9xjls3VjgxyfAlDcxzUFTzqhO6WqEtInH5ZOK44WxGJYvglxYjH4ExYGJT+F9ndnhZ/i6INajPxu6Rvke/zMPJihsqExjytxllvt6vovRmw6+N48CZy3hZBuEzRP,iv:lLKXMfntZUj2f9UJo90PfD4SbabWlC/tSQ/iC6VgGyY=,tag:DvhoW53b+XfPEVhB5MjzdQ==,type:str]
age-secret-key: ENC[AES256_GCM,data:Cmh0C+GBAz+GVtwh650JhQhwPX6jWm4w8UJUZ6kM1+qPoKEJmtGL6r716B0e+SZqyqbieS/lGfCl62TwbboQOs1gEOREkHJHOrI=,iv:CP3/1MoMGqRxj4VsF8++s3PbudtxR10kVPfNMHmw9sw=,tag:1nEHi2PvGKTaLLL5oXvhkQ==,type:str]
sops:
  age:
    - recipient: age170d6z6qazdvz3jtj90p8wrgw8j2vjqqa55jq8mkegkzrf4ch343qhjdfwg
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPSGtBSkY2ZWxFK3JwekNY
        RkZLaktOcnNmWUVORHZwc0srWXREemcwS0Y4CkVOelRHWkI1cWptSmRmNktoTUFN
        K3VYQkJyalMwTnRRb0NQdkI1dHpRUzQKLS0tIEtTMzJFQitmTVdRQ1F0Z3F5WllR
        ajBaNkhnZHpKOG1TQ1BhUWVUUHVFUncKEv+3K5V7aIMyPmrEnMspGodZkHetSLAn
        aTD3RArXoZjbqmFqTwjW0KhvAm/jqmCDvh32OVX1TwksNBRKNg1o0A==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1fuedjsnapm4peln3ke9aq8rr3nvacke65gfhzqd8cg72qd7ntskq25yn2e
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlNENrWHByMmgwK2N5cmRj
        RjF6OWNDdjBkbnN4emlqRHBpMTFmTkZWbFRrCkdhOVBuWEpDYkxyejNZS3JJRi9Q
        b1c3QjBNZVE4cTA5VVdBU2xLeXczTTgKLS0tIDZGZVllM1k5aFpuRG9IaldTU1FS
        N014UmJyT2orWHR4amg3Y2hpaUZHVXcKLEbT/mPEk1cCwt/y1PnYdMEjdFRbWmr7
        fLNOumV7doa6UdS1ATkgOQ5ahq+GkUrsR1xDl87vJ6Er+Tzo/GWNKQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1w7xxgnxeuj37mdpq27wqhpf3td3rwnjtlcxgauvdyget8yfuuf3sax65tw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOcXAxMHBTSnQwSk1RVjl4
        bm43YUFFZ1JudGszcEsvbDVOYytvZHhESms4CnZMUjZOVEFSL3oxc0dFWERlYWNi
        czdMRUJVcEJhK25tRUQ3K2M1REZrbzAKLS0tIFNYcXpjR0RLMENhQjlMT0E4RElQ
        R1JRNGEzNFFGRDdtblFOMkpXeUE1ZDQKgjjK48gtv6P/Yc+urQdf7GRrPdVJdasJ
        u75i8L28hC5376Bzn60rR+y4ljyf3dspgEJ9QiuwKdUQEkAbXzuIQw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1l5uf3k2x5z0eprxhy5x7pvjt4pvtph6j4jct9sr6z07mupus3v3qjyu72w
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4ZkFHS05SZ2kzQzlzck5m
        QXYzdU0wMmV6UWdQelNWQ2pjaDljaU9vOEZVClcrYjE5bzN4KzlZeit2ekQ5KzZG
        aGdhSEhBNVBDbUlsK2J1bFhCYjMrWVUKLS0tIENxZ0dOQ3N2N1FHdXZEaitWa0VK
        bmtuUWlZa1M4YnBjS25xTlJEeG5hQjQKBRsANOXu5PU2m4NlUhquy3qMV6MyyfkJ
        Kw/EShvurLilVkQzuWRvKDzrUiHcE5OYp1AOw/1KpEcTHgT1ExXI1A==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1zmyz7jedkp8kvkct2tgxg38t0cugn0crms6wjkv46xwnr8ycca4qn9vupe
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaYlBQNjV5UFdLMU5kdHhG
        R0dvNTJvM1VWT2c5UFFnUlMzTVhmWEtTY3pZCm9RQVJkNHAwR1pwRzZoS2k2bnA5
        NGErbGtyNXdNSDFsSHVrVEFiRm9JYXcKLS0tIDF0ZGF4R1M1b1llazNWNWVqaDhs
        cG1YUVgyYTEzOFgrTkxmbFo0cWVONzAKjAbNxjbZmcsGm2jAmGZxrC9Gf7CL4Rs5
        W1cJzPWMhk67nSqSrNHca2/G3Q5fxB04CngUgD0GfwM35Wt4ngzn7w==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age163zae0wt5vvvuuxdlxvt68zezyufu6dwz6ax5z7lk26kemypv9ws0pvldy
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRMFhicWxqaTN0VFoybHJm
        Uy9aMytXVktLR3dtWERCb0lVSlpWakNZQnpzClN3MHh1b3dPOVplc0t0TFMvbWNJ
        WnhiRzl2cXZGaURVSDZXMkJUL1ByTlUKLS0tIFBTaHFCNVVyZTBSNGpaWDd4Qnp3
        RjJyT01Edksra3Q3VFFkVHBUdHlWWU0KJiv57/Xcz2iCbvlOalheHLPtiVQEY7+v
        ffDckn4YnhPUJaN7W/cKgcjr4/BZ7GtPG/9KS3k83XdMovbaPCpOXw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1axm5yfnhst7wxh7cgcm43wfdq4t80jaekgrfqqmprmzglqhrhdasjtmc97
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBckR3M3hHSmZsdk15dWRs
        c1RUZmsyV3V4QjBVclQyN1VwTmVhWU54aldNCmhnRFVUaFVSNkpGUkV3WThlTjUr
        UmVoU1Z6NmVCa2RrQmVjcnlUNnUyWnMKLS0tIEVCNjJSNVYrS2JBWGRDNzk3Sjdm
        S0syZW85UGs2QVc2VCt3M2NqQWZSaXcKAqKPTpTNQ4GWoPjfgcFLLJlgrqtr4001
        08+P/sApk+aa5h/dLoYpEYHeCCH2Bx6ahXpGKsd3eI9HNA6d0W7dbA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-11T01:50:52Z"
  mac: ENC[AES256_GCM,data:z/aqo0nhyKNtDTWv8RGjxAheKymtHxu9y6Wf1isu/5Au3tLbeguW4O/KoHwSqhAH0h7wRuA0lLakMq6WlR0YlRdjDbbqCKmwBMlttiEHq+IeP51oRwIJHDp5OJCm4J0xojRfqz4RxKXxqlGpXVh7Klb2JcO4Hc56XzytTYuyF18=,iv:PImJvudf9dHdxJ7xc4rmiflccvcbd1SfL7gPa1aWDHM=,tag:n78wbZFadRuwdf3VVBTWQA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.10.2
