login-password: ENC[AES256_GCM,data:UNR97jSHa3D7RKebhiHJZyXxjI+8RYV5UHVHgXTKLSBUBBNhoJ60Nsctlldle1+rctMszr3F5RYTjUL/gFHBMZVZfllZyXzh5w==,iv:/9uLUaN2rBcfWJoBlBvoLeLu7DUEDgAh7fOqJBD8KFw=,tag:FQNmdbR45kPhvZJ5OTYf6A==,type:str]
tailscale-authkey: ENC[AES256_GCM,data:eWDApsDovofu9+NSAnjz2wsqVQw0FZ6mA/SvJXDDs+PX4FNYgD63cqMELnA4jkuj7BsOja6hifDNVBBAhA==,iv:H6BSnkkc1tk53/2J9UrXjDxD17RhZA1FsbasNC09DTs=,tag:1wofAmidN5KhGxh/LD43dQ==,type:str]
age-public-key: ENC[AES256_GCM,data:GXYQ1WSi1hxdrJ9uH/6LE36KOVluVTA/aexze6RDwX690uNCxatkcwhY6jPXE91kDpCPm7M5KDfPb00cC4d/JofmMOdDDWgCeT84cI9Z1I5fL7lmqUhy1wQkHYdKZ3w7wxbKdpv5sSLskdAC6L4XTF3HgjJhtAqFtwLA0PI6,iv:lLKXMfntZUj2f9UJo90PfD4SbabWlC/tSQ/iC6VgGyY=,tag:8B+rETsMSOWCCGHD6XtAGg==,type:str]
age-secret-key: ENC[AES256_GCM,data:MkjqVFBXcPUepismIpLV9t6HUWeCNeJ2yJ7oU+ZPZuCr3hEV6ZwBccA4S4D/6bFqDOY6DLTm0n7DsbsLQa2+WJykOlYHWFSvGnk=,iv:CP3/1MoMGqRxj4VsF8++s3PbudtxR10kVPfNMHmw9sw=,tag:KKgyRYoCLDP2+TVQBXPKzw==,type:str]
sops:
  age:
    - recipient: age170d6z6qazdvz3jtj90p8wrgw8j2vjqqa55jq8mkegkzrf4ch343qhjdfwg
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmYjB3WERLejRXYXdSTDRM
        TForeDVVT1pQQjVCL3ZhbklKOUhJMEhiL0VnCnUrTEw5UG1zakI2NjVpcStSUTM3
        aGljZ1F5REdaUTJvRXRTYTdpakVOZmcKLS0tIHhGTHJPRlM2N094c1NTeFIzZ214
        S08rYVExQlFxWUlNZzdyYkMwS0UrMFkKxX/HM/IbabJlMBcLojIxltFuljCXWR7P
        RaWTKmtBCBqoim88By4Mb0lqn89IIc9g2ausiGTCpZcsw3BYEge8Ww==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1w7xxgnxeuj37mdpq27wqhpf3td3rwnjtlcxgauvdyget8yfuuf3sax65tw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArbVcyZ2phSDRyM3hXUitO
        QW1GS0xmNm1KWWx4ZWpWMmlUY01Jc2pjcjNVClIveVZyL3BidGlvbGM3eVdKT2NH
        Q1ZYdUxTZDc5OW5SSHFPUjhmNCs5RWsKLS0tIFJNRTcrRVl2NDEzNS9oN0N5a0Ju
        alJnRVYzL0w1djNDNFpyU3IyTERqMmcKpMxHP0hMe0E3nMzwY8e7o8etLuq7jc09
        OuqXW4pgtTa9T2pNkw5nJnP5CgexR2Fras8owes4LD1dxRrnpPwUDg==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1l5uf3k2x5z0eprxhy5x7pvjt4pvtph6j4jct9sr6z07mupus3v3qjyu72w
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpQW9KbVp1OG5ibjl2cXhC
        N1FocExSZ0dKVlVacUorZmhlQXIvV3dITlM0ClJpVFlJR00xN0hoajVkOW9kYklv
        RVpGUTF0T21COE9LRGYxTTNKZ2w4YjAKLS0tIDR1UnR3MGltUmNVSFdqT3dsS2Ry
        MzJ2NTVOWkI2VTFDODVuMXhSeGNhKzgKdNrkSz6SIEoZyeXbYV77Zbv2KNGLA4hW
        UVonFApGa3EtEp15iPAhFim1OEEMaGS+UpqSf8WC98CmjSmqeUb+tA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1xddge8ga0ra6fshfjtecfw00kexytlu0n6smj0yyjla4zd795g9qe6lfjr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVdzNXNWJLSGdNSXIvVktQ
        QmZYTHI1WW1mdXZoNlAvSk9ISk4vOEdNbVJZCitRUlpoQXJGQWtQSWdGZWF3VWYv
        WkJoQ1lhZWUrT0p5YjF6SzVmRFowUVUKLS0tIE82a3NUMUx2UUwraGF4NlQ4TCtZ
        Y0J4bUlrZ0Nla3BjWElNS3AreFY0eFEKbDCo9/yyaTEqZc1JVuVm6BzA0IuqRjqL
        E3FOcsBYbBr3pB/elyMYNQXcX22gDW4NDU0MPLy1+Z0WlAOQCE2hYw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age163zae0wt5vvvuuxdlxvt68zezyufu6dwz6ax5z7lk26kemypv9ws0pvldy
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtYnlxRWg5VkMwdFJBT01S
        UG1DUjFJUndSeEFjRkQ1YnlGd1hiaE9rOUJVCmM2NzcvLzRSTlpYcnpjaXhqOWV1
        S2xyc25JQnovRVFobkJHR3dyelZkblkKLS0tIHBRSVRNZGRlQkxLVFpQb014dXdl
        QWVNK1JTNTBaaEhzRVprQzIyT2NUejAKRur1pPzyVsA7katIAchq7bu3X3gQlMni
        b4XHGmAwC0K7hENSLIE/Bg+tFkDSTJX1MuzQGuM3+bTafjmGaeeRmA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1axm5yfnhst7wxh7cgcm43wfdq4t80jaekgrfqqmprmzglqhrhdasjtmc97
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0RnUyYnFFQzlYZXJwQ1Zp
        VVBMM1hSM0pCNUV6QkR6aFhCZE1XU2xCdDFBCnBKZGNEejBDUnU1ekRYc053aGY1
        VFdXc0Y4a2d0Vk5EanV6a0l3REhUL0EKLS0tIDJhektXUW03dFZDdnQvL0NqdkFD
        amR5ckRZZlJUMm1NSWR2RDlZZVVIZEEKucIVd12qQuyKx3zjwYeNzclwp8Tkq3kL
        2hzMQlTCCFLVOGN4232NSPnuwNsb5XO59plNmr2KZ31bd5SM1j46cw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-15T04:10:29Z"
  mac: ENC[AES256_GCM,data:lbqB9kAyr8Qi0Aq/YWtBRbqZicvSW//zoxx13f9fyEtYmgxLkeEEGUyASgUYBhhJZBY7pJxZAmAxgDRYv1UjwvN33yfgupBgU99KkGQAHiXVe9ojJu/vf6srL6DxriBtTKv5QQ5hUVKOQCnkmQTWcGK2c6ozxkVUzufi9fJPFQw=,iv:8/z+VYLQiksaUxvO6lYBI1c8FTKk3kYJFFPh5IYH3Xw=,tag:ncaNR/iV+h4SmN1Nzzl/eA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
