login-password: ENC[AES256_GCM,data:4/zjSvn0JBFrxjLcbMQHdZnqC2SfQIGDjOf8hScX8W1Yc2E9KGqTUqagLyDKUJWSgfG9z3xFlvi8hltOzA2CGkaA9k5s529R6A==,iv:/9uLUaN2rBcfWJoBlBvoLeLu7DUEDgAh7fOqJBD8KFw=,tag:br909IOYkQdyPdjEdEDSxg==,type:str]
tailscale-authkey: ENC[AES256_GCM,data:rnNe2KvkWtQKF7n6hUR6UFNeu6bP/OVLvZ5aFJ0/d8+aAOLXCjpHWBPcqZ4AjAG7MZibei1mG0Ey4eiODQ==,iv:H6BSnkkc1tk53/2J9UrXjDxD17RhZA1FsbasNC09DTs=,tag:abAQTxGpq+kzlDh0lmGm0g==,type:str]
age-public-key: ENC[AES256_GCM,data:eHfTFfnki8RQL+RTGLbjQmsMaqeUNpiJY8nnhPZYczGx9xjls3VjgxyfAlDcxzUFTzqhO6WqEtInH5ZOK44WxGJYvglxYjH4ExYGJT+F9ndnhZ/i6INajPxu6Rvke/zMPJihsqExjytxllvt6vovRmw6+N48CZy3hZBuEzRP,iv:lLKXMfntZUj2f9UJo90PfD4SbabWlC/tSQ/iC6VgGyY=,tag:DvhoW53b+XfPEVhB5MjzdQ==,type:str]
age-secret-key: ENC[AES256_GCM,data:Cmh0C+GBAz+GVtwh650JhQhwPX6jWm4w8UJUZ6kM1+qPoKEJmtGL6r716B0e+SZqyqbieS/lGfCl62TwbboQOs1gEOREkHJHOrI=,iv:CP3/1MoMGqRxj4VsF8++s3PbudtxR10kVPfNMHmw9sw=,tag:1nEHi2PvGKTaLLL5oXvhkQ==,type:str]
sops:
  age:
    - recipient: age170d6z6qazdvz3jtj90p8wrgw8j2vjqqa55jq8mkegkzrf4ch343qhjdfwg
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXNVhsQlFzcEdYK2o4WDJI
        YVZRWmZUdXkzdi9QclV3MTJpV0xXcW9jUWpzCktMRDhUb2t1cnpYWElTaWFxUG81
        YjAyWCt4cVFzQzhLU0VYN0RBKzJkMzAKLS0tIEY5TlgybXhodDM0Y2psUW9Dc3Uw
        ZytLZXJSM1NCZ0FQZjMrWlhSSXY5elkK/00S9XZCyFr7SV3dG6RADBNAGEmIXIBx
        0z/DsNhJ3mUHXwW3VBFLxXaVCfv/ahxabRQzb8n7KN+CuNxC9N/M1Q==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1fuedjsnapm4peln3ke9aq8rr3nvacke65gfhzqd8cg72qd7ntskq25yn2e
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBISk0xRlltUm51NUQrTHZM
        VXd0WUJWMGV5N0RqMktvU2lNS3BoWkxZTEJvCkpuajBNL0M1blVCcTVDUTlPSGl2
        ZGVZWnR3WnVDbkRGUUpmU003Z1lPQUUKLS0tIDlxWlZFb1BkZzEwYXpUQ2UyeWQ0
        aHhtWmxHOFpHTTdZT1F3TjRMaWMrTUUKAehkPGovK7nh/9/V4SdimBkRXyaiWYa4
        wTAYOliC5+QXKBpaNZDIJy4uZUIF59A1doWYtjs2as0jSZ057DnVEQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1w7xxgnxeuj37mdpq27wqhpf3td3rwnjtlcxgauvdyget8yfuuf3sax65tw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUWUlrOG5SamxwNTBwSzJE
        ckUvcjg1SE52ajRQckZxUW5XczZwd1BLMWlNCjc2MHBmOVRJNndnK2xoL3RoTU1j
        SEphdkl1M1Q1d21lNVNXTnFFS1J6eTAKLS0tIFAzOTlzNGEyMDdISXdWeDN4U05u
        TjV3M21ZQmowZTZPL0x3V0kwaWozTEkKXG9zvcsoF39xXdzGBlmmuhKpkYGi9oim
        rbCI9vqxxPWibymQ4PRcKDoODQP3Ohynl/wB79ZD4OXntSl6ur8hLA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1l5uf3k2x5z0eprxhy5x7pvjt4pvtph6j4jct9sr6z07mupus3v3qjyu72w
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlU1l2SWh0bDJiODJabDZz
        dmVEdnYvQkIwVVdMMVFFcHozUy8wdk1UMUJJCkl3WGpVNkZxZVBqTVZVblZhS2t2
        andkald1TFpDdUYzeDdoenlCSWdFdmcKLS0tIEJYOXZ1a1Y2b1IyWm9Zei9HdDEr
        bTRQRk94dHNDQTlVei9wRUNZZ3kyU0UKjmaLBs/0oS11vcgkbNKWdddoMvLqZuMA
        iTx2pzIVFhlLTrcavgj/53lpK3wt9BIcmO2rLZpwQupLkoaVitourQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1xddge8ga0ra6fshfjtecfw00kexytlu0n6smj0yyjla4zd795g9qe6lfjr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvaEJFZVRpSHRGby9LN2JS
        Kys0M1M4ai94MGlwNHRvWHZpTU9MZkpTQzJFCnBRazFSaVRNa3hPY05NbG5Pejc1
        T2M4SnZNRUJWMVhneld6czdob2RFRG8KLS0tIDdJTUZxc1JNbndPbnVIckEwTVVy
        MEZlNWkyakpLVGtBbThxTFJGWGhsckUKYHaIyHVdYDWQfXh/fU+mp/flEv7EUSjl
        nFhcUsNXDIT/wmgXfVhW4ZwsFdSMpi9sZARBp9gdvc3tt6mBaoVpTA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age163zae0wt5vvvuuxdlxvt68zezyufu6dwz6ax5z7lk26kemypv9ws0pvldy
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBibVFDQTR1ekFER2thc2lh
        MHIwUUl6UnlWS3Y5d2JCbExWSkZvNWVqTEZvCkxYMm9pazkveXBQVGRlUmlETUxL
        OVNkVFJ6ay8wY3B4bEhoaENjM2VJOTQKLS0tIHIzbmZLOCtaL2JRWU1sSmUvT2NW
        YzA1dlRDYUlPQnVUZkU0ZHBKazJiNlEK9ZXEAYif5F1kD85YrpmWDgQF9eUof0y9
        Rz2VvRUS8QDGqKpD8Qd5P7wjY0wyJenisztQLBW4KDy+jyc6JeGyfw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1axm5yfnhst7wxh7cgcm43wfdq4t80jaekgrfqqmprmzglqhrhdasjtmc97
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArZG41dmhBd2MyOFZQdU1q
        Y2cwcUxvVTFOd0xERmcvNFZyR1R2QU1WcFNvCjQyc0FOZ1RyQjdCTW8xcnBLSHVX
        Um1XWWJjbFR5NmZYa1g3WVRkcUpiaXcKLS0tIGNjSlNRUTVXVElLQmdOSzlqelZ6
        djY5aDNvR2ZpZVV0RHN2TXpqNlp6R1UKXg2tmivBn7DcuV1V/0rTb7WBnRcIHSNC
        hgFhFvKnHWSgQEnyBQUXPN0KDresEHM9TxOsXgTKgD7QJO3zpChhnA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-27T03:51:31Z"
  mac: ENC[AES256_GCM,data:oYXXD2QGk29djCel86qke0WGMwjcF4waEcRhSXyxCU1iD4DsnOPTwkw8f7aBPPX9rFHKkPCJxkZgkQqFtPcy5jJejEoWOS4HygWzpxwms5/AdJUZa1+0Mj+LKYkGkwBjwrXLwPP4iv1AbMiRoZl99Juj6SSPOEdI1vhLTqTBkPo=,iv:8ksQvpDclTe/0bhhF0UQVvL4MjaL+ko/2eJ9VGzG0iw=,tag:rJPvKD+9AW5N+0cM/8p13Q==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
